spring.datasource.url=jdbc:postgresql://localhost:5439/ProyectoSoftware01
spring.datasource.username=renind
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.port=8080